### ISSUE TITLE
"http://ggcity.org/h2o/guest/postback" is not working

### ISSUE THREAD

**Issue by geoffk** [ggcity/ggcity.org#30]
When visiting "http://ggcity.org/h2o/guest/postback", I'm getting redirected to "https://ggcity.org/h2o/guest/postback" and then a Rails error.  This is different behavior than in the tests.

**Comment by geoffk** [comment]
Actually, maybe the Rails error part is fine, but it should not redirect.

**Comment by geoffk** [comment]
Same with postback_ivr

**Comment by mooman** [comment]
This should be fine... according to @NoelProf, https redirect is fine.

**Comment by NoelProf** [comment]
Both are working correctly in production, so not an issue now.
