### ISSUE TITLE
is reggister a vocabulary word in search?

### ISSUE THREAD

**Issue by gall0** [ggcity/ggcity.org#62]

**Comment by mooman** [comment]
Synonyms can be added via solr/ggcity-core/conf/synonyms.txt

Is that what you mean?

**Comment by mooman** [comment]
I actually don't think this should be a synonym anymore... i don't think people will search for this specifically. and if they do, it corrects them to search for register instead...

**Comment by mooman** [comment]
Closing... unless there are objections

**Comment by gall0** [comment]
let's kill it

----- Original Message -----
