### ISSUE TITLE
warn about external links and pdfs

### ISSUE THREAD

**Issue by gall0** [ggcity/ggcity.org#77]

**Comment by mooman** [comment]
I feel like that's more annoying than not. You can use CSS query to stylize those links. Might be less intrusive!

    a[href$=".pdf"] {
      ....
    }

Or

    a[href^="http"] {
      ...
    }

**Comment by mooman** [comment]
Fontawesome has some really nice icons to represent these

    a[href^="http"]::after {
      content: "..."
    }

**Comment by gall0** [comment]
¡Eres un genio! 🧞‍♂️ 
----- Original Message -----
