### ISSUE TITLE
Search: FAQ pages are receiving more importance than documentation pages. Do we want this? 

### ISSUE THREAD

**Issue by gall0** [ggcity/ggcity.org#87]
Example: when I search for water the top two results are FAQ pages.

**Comment by gall0** [comment]
Based on 18f recommendations. FAQ pages should not be used. Let's keep an eye on this because they may be a source of confusion and cause more problems than it solves. (duplicate content, irrelevant information)

**Comment by gall0** [comment]
As of launch date we have 19 documentation pages.

**Comment by mooman** [comment]
It's not, but search relevance is also a function of word frequency. I'm guessing the FAQ pages have more frequency in this case than the documentation page.

**Comment by mooman** [comment]
See #91
