### ISSUE TITLE
Police phone number not working

### ISSUE THREAD

**Issue by geoffk** [ggcity/ggcity.org#97]
The x5704 number listed for general information on the police page is going to the IT on-call number.  I don't know if this is a phone problem or if it's the wrong number.  

Maybe it should be x5003?   That's what's listed in the phone book.

https://ggcity.org/police

**Comment by geoffk** [comment]
Actually, we should check with PD to see what number they want, assuming it's not just a phone problem.

**Comment by geoffk** [comment]
Never mind.  The guy who called me was confused.

**Comment by mooman** [comment]
Lol
